# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  ENTRYPOINT_DIR: "."

tasks:
  start:
    desc: Run the server
    cmds:
      - go run {{ .ENTRYPOINT_DIR }}

  generate-docs:
    desc: Use swaggo/swag to run the swag binary to generate API documentation from Swagger annotations
    cmds:
      - swag init
